/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Persistencia.PesquisaDao;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Wukong
 */
public class PesquisaFrame extends javax.swing.JFrame {

    /**
     * Creates new form PesquisaFrame
     */
    public PesquisaFrame() {
        initComponents();
        setDefaultCloseOperation(PesquisaFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTituloPesquisa = new javax.swing.JPanel();
        jLabelTituloPesquisa = new javax.swing.JLabel();
        jPanelMenuPesquisa = new javax.swing.JPanel();
        ToolBarMenuPesquisa = new javax.swing.JToolBar();
        jButtonConsultar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButtonLimpar = new javax.swing.JButton();
        jPanelBodyPesquisa = new javax.swing.JPanel();
        jComboBoxRegistroVendedor = new javax.swing.JComboBox();
        jComboBoxDataVenda = new javax.swing.JComboBox();
        jComboBoxVenda = new javax.swing.JComboBox();
        jPanelAdicionais = new javax.swing.JPanel();
        jScrollPanelAdicionais = new javax.swing.JScrollPane();
        jTableAdicionais = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanelTituloPesquisa.setBackground(new java.awt.Color(255, 255, 255));

        jLabelTituloPesquisa.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelTituloPesquisa.setIcon(new javax.swing.ImageIcon("C:\\Users\\Wukong\\Desktop\\Arquivos\\Google Drive\\Git\\UCB.LPIV.Concessionaria\\src\\Visao\\Imagens\\pesquisa.png")); // NOI18N
        jLabelTituloPesquisa.setText("Pesquisa");

        javax.swing.GroupLayout jPanelTituloPesquisaLayout = new javax.swing.GroupLayout(jPanelTituloPesquisa);
        jPanelTituloPesquisa.setLayout(jPanelTituloPesquisaLayout);
        jPanelTituloPesquisaLayout.setHorizontalGroup(
            jPanelTituloPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTituloPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTituloPesquisa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTituloPesquisaLayout.setVerticalGroup(
            jPanelTituloPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTituloPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTituloPesquisa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelMenuPesquisa.setBackground(new java.awt.Color(204, 204, 204));

        ToolBarMenuPesquisa.setBackground(new java.awt.Color(204, 204, 204));
        ToolBarMenuPesquisa.setRollover(true);

        jButtonConsultar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonConsultar.setText("Consultar");
        jButtonConsultar.setFocusable(false);
        jButtonConsultar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonConsultar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarActionPerformed(evt);
            }
        });
        ToolBarMenuPesquisa.add(jButtonConsultar);
        ToolBarMenuPesquisa.add(jSeparator1);

        jButtonLimpar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.setFocusable(false);
        jButtonLimpar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonLimpar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });
        ToolBarMenuPesquisa.add(jButtonLimpar);

        javax.swing.GroupLayout jPanelMenuPesquisaLayout = new javax.swing.GroupLayout(jPanelMenuPesquisa);
        jPanelMenuPesquisa.setLayout(jPanelMenuPesquisaLayout);
        jPanelMenuPesquisaLayout.setHorizontalGroup(
            jPanelMenuPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ToolBarMenuPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelMenuPesquisaLayout.setVerticalGroup(
            jPanelMenuPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ToolBarMenuPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelBodyPesquisa.setBackground(new java.awt.Color(204, 204, 204));
        jPanelBodyPesquisa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N

        jComboBoxRegistroVendedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione Registro Vendedor" }));
        jComboBoxRegistroVendedor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxRegistroVendedorItemStateChanged(evt);
            }
        });

        jComboBoxDataVenda.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione Data Venda", " " }));

        jComboBoxVenda.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione Codigo Venda", " " }));

        javax.swing.GroupLayout jPanelBodyPesquisaLayout = new javax.swing.GroupLayout(jPanelBodyPesquisa);
        jPanelBodyPesquisa.setLayout(jPanelBodyPesquisaLayout);
        jPanelBodyPesquisaLayout.setHorizontalGroup(
            jPanelBodyPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBodyPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxRegistroVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBodyPesquisaLayout.setVerticalGroup(
            jPanelBodyPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBodyPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBodyPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxRegistroVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelAdicionais.setBackground(new java.awt.Color(204, 204, 204));
        jPanelAdicionais.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações Adicionais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N

        jScrollPanelAdicionais.setBackground(new java.awt.Color(204, 204, 204));

        jTableAdicionais.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTableAdicionais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "QTD de Vendas", "Valor Total de Vendas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableAdicionais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAdicionaisMouseClicked(evt);
            }
        });
        jScrollPanelAdicionais.setViewportView(jTableAdicionais);

        javax.swing.GroupLayout jPanelAdicionaisLayout = new javax.swing.GroupLayout(jPanelAdicionais);
        jPanelAdicionais.setLayout(jPanelAdicionaisLayout);
        jPanelAdicionaisLayout.setHorizontalGroup(
            jPanelAdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPanelAdicionais, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanelAdicionaisLayout.setVerticalGroup(
            jPanelAdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPanelAdicionais, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTituloPesquisa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelMenuPesquisa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelBodyPesquisa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelAdicionais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelTituloPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanelMenuPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBodyPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelAdicionais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarActionPerformed

    }//GEN-LAST:event_jButtonConsultarActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
         PesquisaControle controle = new PesquisaControle();
        controle.limparTela(this);
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jTableAdicionaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAdicionaisMouseClicked

    }//GEN-LAST:event_jTableAdicionaisMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            PesquisaDao dao = new PesquisaDao();
            dao.preencherComboVendedor(this);
        } catch (SQLException ex) {
            Logger.getLogger(PesquisaFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void jComboBoxRegistroVendedorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxRegistroVendedorItemStateChanged
        try {
            PesquisaDao dao = new PesquisaDao();
            dao.preencherJTableAdicionais(this);
        } catch (SQLException ex) {
            Logger.getLogger(PesquisaFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jComboBoxRegistroVendedorItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesquisaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesquisaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesquisaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesquisaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PesquisaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar ToolBarMenuPesquisa;
    private javax.swing.JButton jButtonConsultar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JComboBox jComboBoxDataVenda;
    private javax.swing.JComboBox jComboBoxRegistroVendedor;
    private javax.swing.JComboBox jComboBoxVenda;
    private javax.swing.JLabel jLabelTituloPesquisa;
    private javax.swing.JPanel jPanelAdicionais;
    private javax.swing.JPanel jPanelBodyPesquisa;
    private javax.swing.JPanel jPanelMenuPesquisa;
    private javax.swing.JPanel jPanelTituloPesquisa;
    private javax.swing.JScrollPane jScrollPanelAdicionais;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JTable jTableAdicionais;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the jComboBoxDataVenda
     */
    public javax.swing.JComboBox getjComboBoxDataVenda() {
        return jComboBoxDataVenda;
    }

    /**
     * @param jComboBoxDataVenda the jComboBoxDataVenda to set
     */
    public void setjComboBoxDataVenda(javax.swing.JComboBox jComboBoxDataVenda) {
        this.jComboBoxDataVenda = jComboBoxDataVenda;
    }

    /**
     * @return the jComboBoxRegistroVendedor
     */
    public javax.swing.JComboBox getjComboBoxRegistroVendedor() {
        return jComboBoxRegistroVendedor;
    }

    /**
     * @param jComboBoxRegistroVendedor the jComboBoxRegistroVendedor to set
     */
    public void setjComboBoxRegistroVendedor(javax.swing.JComboBox jComboBoxRegistroVendedor) {
        this.jComboBoxRegistroVendedor = jComboBoxRegistroVendedor;
    }

    /**
     * @return the jComboBoxVenda
     */
    public javax.swing.JComboBox getjComboBoxVenda() {
        return jComboBoxVenda;
    }

    /**
     * @param jComboBoxVenda the jComboBoxVenda to set
     */
    public void setjComboBoxVenda(javax.swing.JComboBox jComboBoxVenda) {
        this.jComboBoxVenda = jComboBoxVenda;
    }

    /**
     * @return the jTableAdicionais
     */
    public javax.swing.JTable getjTableAdicionais() {
        return jTableAdicionais;
    }

    /**
     * @param jTableAdicionais the jTableAdicionais to set
     */
    public void setjTableAdicionais(javax.swing.JTable jTableAdicionais) {
        this.jTableAdicionais = jTableAdicionais;
    }
}
