/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.ProdutoAlterarControle;
import Persistencia.ProdutoAlterarDao;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Wukong
 */
public class ProdutoAlterarFrame extends javax.swing.JFrame {

    /**
     * Creates new form ProdutoAlterarFrame
     */
    public ProdutoAlterarFrame() {
        initComponents();
        setDefaultCloseOperation(ProdutoAlterarFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMenuTurma = new javax.swing.JPanel();
        jToolBarMenuTurma = new javax.swing.JToolBar();
        jButtonAtualizarTurmaAlterar = new javax.swing.JButton();
        jButtonLimparTurmaAlterar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelCodigoCarro = new javax.swing.JLabel();
        jLabelMarca = new javax.swing.JLabel();
        jLabelModelo = new javax.swing.JLabel();
        jLabelPreco = new javax.swing.JLabel();
        jTextFieldMarca = new javax.swing.JTextField();
        jTextFieldModelo = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelAno = new javax.swing.JLabel();
        jTextFieldAno = new javax.swing.JTextField();
        jLabelCor = new javax.swing.JLabel();
        jTextFieldCor = new javax.swing.JTextField();
        jComboBoxCodigo = new javax.swing.JComboBox();
        jTextFieldPreco = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanelMenuTurma.setBackground(new java.awt.Color(204, 204, 204));

        jToolBarMenuTurma.setBackground(new java.awt.Color(204, 204, 204));
        jToolBarMenuTurma.setRollover(true);

        jButtonAtualizarTurmaAlterar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonAtualizarTurmaAlterar.setText("Atualizar");
        jButtonAtualizarTurmaAlterar.setFocusable(false);
        jButtonAtualizarTurmaAlterar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAtualizarTurmaAlterar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonAtualizarTurmaAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarTurmaAlterarActionPerformed(evt);
            }
        });
        jToolBarMenuTurma.add(jButtonAtualizarTurmaAlterar);

        jButtonLimparTurmaAlterar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonLimparTurmaAlterar.setText("Limpar");
        jButtonLimparTurmaAlterar.setFocusable(false);
        jButtonLimparTurmaAlterar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonLimparTurmaAlterar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonLimparTurmaAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparTurmaAlterarActionPerformed(evt);
            }
        });
        jToolBarMenuTurma.add(jButtonLimparTurmaAlterar);

        javax.swing.GroupLayout jPanelMenuTurmaLayout = new javax.swing.GroupLayout(jPanelMenuTurma);
        jPanelMenuTurma.setLayout(jPanelMenuTurmaLayout);
        jPanelMenuTurmaLayout.setHorizontalGroup(
            jPanelMenuTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuTurmaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBarMenuTurma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelMenuTurmaLayout.setVerticalGroup(
            jPanelMenuTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuTurmaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBarMenuTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Atualizar Carro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N

        jLabelCodigoCarro.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabelCodigoCarro.setText("Codigo Carro");

        jLabelMarca.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabelMarca.setText("Marca");

        jLabelModelo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabelModelo.setText("Modelo");

        jLabelPreco.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabelPreco.setText("Preço");

        jTextFieldMarca.setColumns(20);

        jTextFieldModelo.setColumns(10);

        jLabelAno.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabelAno.setText("Ano");

        jTextFieldAno.setColumns(20);

        jLabelCor.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabelCor.setText("Cor");

        jTextFieldCor.setColumns(2);

        jComboBoxCodigo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jComboBoxCodigo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione Codigo" }));
        jComboBoxCodigo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxCodigoItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelCodigoCarro)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelModelo)
                                    .addComponent(jLabelMarca)
                                    .addComponent(jLabelCor)
                                    .addComponent(jLabelAno)
                                    .addComponent(jLabelPreco))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextFieldPreco, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldCor, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldAno, javax.swing.GroupLayout.Alignment.LEADING)))))
                        .addGap(50, 50, 50)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodigoCarro)
                    .addComponent(jComboBoxCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMarca))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelModelo)
                    .addComponent(jTextFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAno)
                    .addComponent(jTextFieldAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCor)
                    .addComponent(jTextFieldCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPreco)
                    .addComponent(jTextFieldPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMenuTurma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelMenuTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAtualizarTurmaAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarTurmaAlterarActionPerformed
        ProdutoAlterarControle controle = new ProdutoAlterarControle();
        try {
            controle.Atualizar(this);
        } catch (SQLException ex) {
            Logger.getLogger(ProdutoAlterarFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonAtualizarTurmaAlterarActionPerformed

    private void jButtonLimparTurmaAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparTurmaAlterarActionPerformed
        ProdutoAlterarControle controle = new ProdutoAlterarControle();
        controle.limparTela(this);
    }//GEN-LAST:event_jButtonLimparTurmaAlterarActionPerformed

    private void jComboBoxCodigoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxCodigoItemStateChanged
        try {
            ProdutoAlterarDao dao = new ProdutoAlterarDao();
            dao.preencherCodigoText(this);
        } catch (SQLException ex) {
            Logger.getLogger(ProdutoAlterarFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jComboBoxCodigoItemStateChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            ProdutoAlterarDao dao = new  ProdutoAlterarDao();
            dao.preencherComboCodigo(this);
        } catch (SQLException ex) {
            Logger.getLogger(ProdutoAlterarFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdutoAlterarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdutoAlterarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdutoAlterarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdutoAlterarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProdutoAlterarFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizarTurmaAlterar;
    private javax.swing.JButton jButtonLimparTurmaAlterar;
    private javax.swing.JComboBox jComboBoxCodigo;
    private javax.swing.JLabel jLabelAno;
    private javax.swing.JLabel jLabelCodigoCarro;
    private javax.swing.JLabel jLabelCor;
    private javax.swing.JLabel jLabelMarca;
    private javax.swing.JLabel jLabelModelo;
    private javax.swing.JLabel jLabelPreco;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelMenuTurma;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextFieldAno;
    private javax.swing.JTextField jTextFieldCor;
    private javax.swing.JTextField jTextFieldMarca;
    private javax.swing.JTextField jTextFieldModelo;
    private javax.swing.JTextField jTextFieldPreco;
    private javax.swing.JToolBar jToolBarMenuTurma;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the jTextFieldAno
     */
    public javax.swing.JTextField getjTextFieldAno() {
        return jTextFieldAno;
    }

    /**
     * @param jTextFieldAno the jTextFieldAno to set
     */
    public void setjTextFieldAno(javax.swing.JTextField jTextFieldAno) {
        this.jTextFieldAno = jTextFieldAno;
    }

    /**
     * @return the jTextFieldCor
     */
    public javax.swing.JTextField getjTextFieldCor() {
        return jTextFieldCor;
    }

    /**
     * @param jTextFieldCor the jTextFieldCor to set
     */
    public void setjTextFieldCor(javax.swing.JTextField jTextFieldCor) {
        this.jTextFieldCor = jTextFieldCor;
    }

    /**
     * @return the jTextFieldMarca
     */
    public javax.swing.JTextField getjTextFieldMarca() {
        return jTextFieldMarca;
    }

    /**
     * @param jTextFieldMarca the jTextFieldMarca to set
     */
    public void setjTextFieldMarca(javax.swing.JTextField jTextFieldMarca) {
        this.jTextFieldMarca = jTextFieldMarca;
    }

    /**
     * @return the jTextFieldModelo
     */
    public javax.swing.JTextField getjTextFieldModelo() {
        return jTextFieldModelo;
    }

    /**
     * @param jTextFieldModelo the jTextFieldModelo to set
     */
    public void setjTextFieldModelo(javax.swing.JTextField jTextFieldModelo) {
        this.jTextFieldModelo = jTextFieldModelo;
    }

    /**
     * @return the jTextFieldPreco
     */
    public javax.swing.JTextField getjTextFieldPreco() {
        return jTextFieldPreco;
    }

    /**
     * @param jTextFieldPreco the jTextFieldPreco to set
     */
    public void setjTextFieldPreco(javax.swing.JTextField jTextFieldPreco) {
        this.jTextFieldPreco = jTextFieldPreco;
    }

    /**
     * @return the jComboBoxCodigo
     */
    public javax.swing.JComboBox getjComboBoxCodigo() {
        return jComboBoxCodigo;
    }

    /**
     * @param jComboBoxCodigo the jComboBoxCodigo to set
     */
    public void setjComboBoxCodigo(javax.swing.JComboBox jComboBoxCodigo) {
        this.jComboBoxCodigo = jComboBoxCodigo;
    }

}
