/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.VendaControle;
import Modelo.Venda;
import Persistencia.VendaDao;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Wukong
 */
public class VendaFrame extends javax.swing.JFrame {

    /**
     * Creates new form VendaFramé
     */
    public VendaFrame() {
        initComponents();
        setDefaultCloseOperation(VendaFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTituloVenda = new javax.swing.JPanel();
        LabelTituloVenda = new javax.swing.JLabel();
        jPanelMenuVenda = new javax.swing.JPanel();
        ToolBarMenuAula = new javax.swing.JToolBar();
        jButtonConsultar = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButtonSalvar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jPanelBodyAula = new javax.swing.JPanel();
        jLabelData = new javax.swing.JLabel();
        jDateChooserVenda = new com.toedter.calendar.JDateChooser();
        jLabelRegistroVendedor = new javax.swing.JLabel();
        jTextFieldRegistroVendedor = new javax.swing.JTextField();
        jLabelProduto = new javax.swing.JLabel();
        jComboBoxProduto = new javax.swing.JComboBox();
        jLabelDesconto = new javax.swing.JLabel();
        jTextFieldDesconto = new javax.swing.JTextField();
        jLabelValorAcessorio = new javax.swing.JLabel();
        jTextFieldValorAcessorio = new javax.swing.JTextField();
        jLabelvalorProduto = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableVenda = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanelTituloVenda.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTituloVenda.setAutoscrolls(true);
        jPanelTituloVenda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanelTituloVendaFocusGained(evt);
            }
        });

        LabelTituloVenda.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        LabelTituloVenda.setIcon(new javax.swing.ImageIcon("C:\\Users\\Wukong\\Desktop\\Arquivos\\Google Drive\\Git\\UCB.LPIV.Concessionaria\\src\\Visao\\Imagens\\sale.jpg")); // NOI18N
        LabelTituloVenda.setText("Venda");

        javax.swing.GroupLayout jPanelTituloVendaLayout = new javax.swing.GroupLayout(jPanelTituloVenda);
        jPanelTituloVenda.setLayout(jPanelTituloVendaLayout);
        jPanelTituloVendaLayout.setHorizontalGroup(
            jPanelTituloVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTituloVendaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelTituloVenda)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTituloVendaLayout.setVerticalGroup(
            jPanelTituloVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTituloVendaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelTituloVenda)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelMenuVenda.setBackground(new java.awt.Color(204, 204, 204));
        jPanelMenuVenda.setAutoscrolls(true);

        ToolBarMenuAula.setBackground(new java.awt.Color(204, 204, 204));
        ToolBarMenuAula.setRollover(true);

        jButtonConsultar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonConsultar.setText("Consultar");
        jButtonConsultar.setFocusable(false);
        jButtonConsultar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonConsultar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarActionPerformed(evt);
            }
        });
        ToolBarMenuAula.add(jButtonConsultar);

        jButtonAlterar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonAlterar.setText("Alterar");
        jButtonAlterar.setFocusable(false);
        jButtonAlterar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAlterar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });
        ToolBarMenuAula.add(jButtonAlterar);

        jButtonExcluir.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setFocusable(false);
        jButtonExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        ToolBarMenuAula.add(jButtonExcluir);
        ToolBarMenuAula.add(jSeparator1);

        jButtonSalvar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setFocusable(false);
        jButtonSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        ToolBarMenuAula.add(jButtonSalvar);

        jButtonLimpar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.setFocusable(false);
        jButtonLimpar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonLimpar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });
        ToolBarMenuAula.add(jButtonLimpar);

        javax.swing.GroupLayout jPanelMenuVendaLayout = new javax.swing.GroupLayout(jPanelMenuVenda);
        jPanelMenuVenda.setLayout(jPanelMenuVendaLayout);
        jPanelMenuVendaLayout.setHorizontalGroup(
            jPanelMenuVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuVendaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ToolBarMenuAula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelMenuVendaLayout.setVerticalGroup(
            jPanelMenuVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuVendaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ToolBarMenuAula, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelBodyAula.setBackground(new java.awt.Color(204, 204, 204));
        jPanelBodyAula.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações de Venda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N
        jPanelBodyAula.setPreferredSize(new java.awt.Dimension(435, 153));

        jLabelData.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabelData.setText("Data");

        jDateChooserVenda.setDateFormatString("yyyy-MM-dd");
        jDateChooserVenda.setInheritsPopupMenu(true);
        jDateChooserVenda.setMinSelectableDate(new java.util.Date(-62135755084000L));

        jLabelRegistroVendedor.setText("Registro Vendedor");

        jLabelProduto.setText("Produto");

        jComboBoxProduto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione Produto" }));
        jComboBoxProduto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxProdutoItemStateChanged(evt);
            }
        });
        jComboBoxProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProdutoActionPerformed(evt);
            }
        });

        jLabelDesconto.setText("Desconto");

        jLabelValorAcessorio.setText("Valor de Acessóios");

        jLabelvalorProduto.setText("Valor Produto");

        javax.swing.GroupLayout jPanelBodyAulaLayout = new javax.swing.GroupLayout(jPanelBodyAula);
        jPanelBodyAula.setLayout(jPanelBodyAulaLayout);
        jPanelBodyAulaLayout.setHorizontalGroup(
            jPanelBodyAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBodyAulaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBodyAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBodyAulaLayout.createSequentialGroup()
                        .addGroup(jPanelBodyAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelProduto)
                            .addComponent(jLabelData))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelBodyAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDateChooserVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxProduto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabelDesconto)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelBodyAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelBodyAulaLayout.createSequentialGroup()
                                .addComponent(jLabelValorAcessorio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldValorAcessorio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelBodyAulaLayout.createSequentialGroup()
                                .addComponent(jLabelRegistroVendedor)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldRegistroVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabelvalorProduto))
                .addContainerGap(263, Short.MAX_VALUE))
        );
        jPanelBodyAulaLayout.setVerticalGroup(
            jPanelBodyAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBodyAulaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBodyAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelBodyAulaLayout.createSequentialGroup()
                        .addComponent(jLabelData)
                        .addGap(7, 7, 7))
                    .addComponent(jDateChooserVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelBodyAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelRegistroVendedor)
                        .addComponent(jTextFieldRegistroVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelBodyAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProduto)
                    .addComponent(jComboBoxProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDesconto)
                    .addComponent(jTextFieldDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelValorAcessorio)
                    .addComponent(jTextFieldValorAcessorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelvalorProduto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane2.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tabela Aula", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N

        jTableVenda.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTableVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CodigoVenda", "Registro Vendedor", "Data", "CodigoProduto", "Desconto", "Valor Acessorios", "Valor Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableVenda);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTituloVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelMenuVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelBodyAula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 935, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelTituloVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelMenuVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBodyAula, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelTituloVendaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanelTituloVendaFocusGained

    }//GEN-LAST:event_jPanelTituloVendaFocusGained

    private void jButtonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarActionPerformed
        try {
            VendaControle controle = new VendaControle();
            controle.consultar(this);
        } catch (SQLException ex) {
            Logger.getLogger(VendaFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonConsultarActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed

    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        VendaControle controle = new VendaControle();
        Venda venda = new Venda();
        controle.Deletar(venda);
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed

        try {
            VendaControle controle = new VendaControle();
            controle.salvarCampos(this);
        } catch (SQLException ex) {
            Logger.getLogger(VendaFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        VendaControle controle = new VendaControle();
        controle.limparTela(this);
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jComboBoxProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxProdutoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            VendaDao dao = new VendaDao();
            dao.preencherComboCodigo(this);
                    } catch (SQLException ex) {
            Logger.getLogger(VendaFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void jComboBoxProdutoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxProdutoItemStateChanged
        
    }//GEN-LAST:event_jComboBoxProdutoItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VendaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelTituloVenda;
    private javax.swing.JToolBar ToolBarMenuAula;
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonConsultar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox jComboBoxProduto;
    private com.toedter.calendar.JDateChooser jDateChooserVenda;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelDesconto;
    private javax.swing.JLabel jLabelProduto;
    private javax.swing.JLabel jLabelRegistroVendedor;
    private javax.swing.JLabel jLabelValorAcessorio;
    private javax.swing.JLabel jLabelvalorProduto;
    private javax.swing.JPanel jPanelBodyAula;
    private javax.swing.JPanel jPanelMenuVenda;
    private javax.swing.JPanel jPanelTituloVenda;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JTable jTableVenda;
    private javax.swing.JTextField jTextFieldDesconto;
    private javax.swing.JTextField jTextFieldRegistroVendedor;
    private javax.swing.JTextField jTextFieldValorAcessorio;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the jComboBoxProduto
     */
    public javax.swing.JComboBox getjComboBoxProduto() {
        return jComboBoxProduto;
    }

    /**
     * @param jComboBoxProduto the jComboBoxProduto to set
     */
    public void setjComboBoxProduto(javax.swing.JComboBox jComboBoxProduto) {
        this.jComboBoxProduto = jComboBoxProduto;
    }

    /**
     * @return the jTableVenda
     */
    public javax.swing.JTable getjTableVenda() {
        return jTableVenda;
    }

    /**
     * @param jTableVenda the jTableVenda to set
     */
    public void setjTableVenda(javax.swing.JTable jTableVenda) {
        this.jTableVenda = jTableVenda;
    }

    /**
     * @return the jTextFieldDesconto
     */
    public javax.swing.JTextField getjTextFieldDesconto() {
        return jTextFieldDesconto;
    }

    /**
     * @param jTextFieldDesconto the jTextFieldDesconto to set
     */
    public void setjTextFieldDesconto(javax.swing.JTextField jTextFieldDesconto) {
        this.jTextFieldDesconto = jTextFieldDesconto;
    }

    /**
     * @return the jTextFieldRegistroVendedor
     */
    public javax.swing.JTextField getjTextFieldRegistroVendedor() {
        return jTextFieldRegistroVendedor;
    }

    /**
     * @param jTextFieldRegistroVendedor the jTextFieldRegistroVendedor to set
     */
    public void setjTextFieldRegistroVendedor(javax.swing.JTextField jTextFieldRegistroVendedor) {
        this.jTextFieldRegistroVendedor = jTextFieldRegistroVendedor;
    }

    /**
     * @return the jTextFieldValorAcessorio
     */
    public javax.swing.JTextField getjTextFieldValorAcessorio() {
        return jTextFieldValorAcessorio;
    }

    /**
     * @param jTextFieldValorAcessorio the jTextFieldValorAcessorio to set
     */
    public void setjTextFieldValorAcessorio(javax.swing.JTextField jTextFieldValorAcessorio) {
        this.jTextFieldValorAcessorio = jTextFieldValorAcessorio;
    }

    /**
     * @return the jDateChooserVenda
     */
    public com.toedter.calendar.JDateChooser getjDateChooserVenda() {
        return jDateChooserVenda;
    }

    /**
     * @param jDateChooserVenda the jDateChooserVenda to set
     */
    public void setjDateChooserVenda(com.toedter.calendar.JDateChooser jDateChooserVenda) {
        this.jDateChooserVenda = jDateChooserVenda;
    }
}
